### ISSUE TITLE
how to install universAAl plugin

### ISSUE THREAD

**Issue by softwareEngineersOrg** [universAAL/tools.eclipse-plugins#447]
Hi,
I would like to install universAAL plugin, but the  https://github.com/universAAL/tools.eclipse-plugins/wiki/universAAL-Studio-overview-and-installation is not correct. There is problem with link http://depot.universaal.org/eclipse-update/4.6 

So, how to install universAAL?

Best regards,
Artur

**Comment by Alfiva** [comment]
Hello Artur,
The issue is that right now the depot.universaal.org domain is not reachable, as reported in #446 . Unfortunately this is taking longer than expected to get back up since it depends on outside entities.
In the meantime I would suggest compiling the tools, but since it requires particular Eclipse versions and it's more complicated than just compiling an OSGi bundle, this may not be a viable solution.
As an alternative, you can create new universaal projects manually as long as they comply with the restrictions. You can simply use as a basis any of the sample code projects from https://github.com/universAAL/samples/tree/master/tutorials or https://github.com/universAAL/samples/tree/master/ont.tutorial
Sorry for the inconvenience

**Comment by saiedt** [comment]
The issue with depot.universaal.org has finally been resolved.
We are so sorry for the long delay: thw server is hosted by Fraunhofer IGD, and after I left Fraunhofer IGD, there was nobody any more to quickly take care. We will try to transfer this server to an organization with universAAL developers, but this again may take some time...
